[package]
name = "heap-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.default-boxed]
version = "0.2.0"
optional = true

[features]
default-boxed = ["dep:default-boxed"]